repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.86.0
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
      args:
        - --hook-config=--create-file-if-not-exist=true
        - --hook-config=--add-to-existing-file=true
        - --hook-config=--path-to-file=README.md
    - id: terraform_tflint
    - id: terraform_validate